add_newline = false
command_timeout = 5000

[character] 
success_symbol = "[➜](bold green)"

[package]
disabled = true

[python]
disabled = true

[aws]
disabled = true

[gcloud]
disabled = true

[terraform]
disabled = true

[elixir]
disabled = true

[custom.elixir]
command = "echo 💧v$(asdf_current elixir)"
files = ["mix.exs"]
style = "bold purple"
format = "via [$output]($style) "
shell = ["bash", "--noprofile", "--norc"]
